# Generated by Django 3.2 on 2021-04-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sticker',
            old_name='keyword',
            new_name='keywords',
        ),
    ]
